apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-deployment
spec:
  selector:
    matchLabels:
      env: production

  replicas: 1
  template:
    metadata:
      labels:
        env: production

    spec:
      containers:
      - name: httpd-container
        image: anshu98/httpd:v1

        ports:
        - containerPort: 80

        volumeMounts:
          - name: httpd-data-volume
            mountPath: /var/www/html/

        volumeMounts:
          - name: httpd-logs-volume
            mountPath: /var/log/httpd/

      volumes:
      - name: httpd-data-volume
        persistentVolumeClaim:
          claimName: web-data-pvc

      volumes:
      - name: httpd-logs-volume
        persistentVolumeClaim:
          claimName: web-log-pvc