apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-deployment
spec:
  selector:
    matchLabels:
      env: production

  replicas: 1
  template:
    metadata:
      labels:
        env: production

    spec:
      containers:
      - name: php-container
        image: anshu98/php:v1

        ports:
        - containerPort: 80

        volumeMounts:
          - name: php-data-volume
            mountPath: /var/www/html/

        volumeMounts:
          - name: php-logs-volume
            mountPath: /var/log/httpd/

      volumes:
      - name: php-data-volume
        persistentVolumeClaim:
          claimName: web-data-pvc

      volumes:
      - name: php-logs-volume
        persistentVolumeClaim:
          claimName: web-log-pvc